### PR TITLE
Fixed the Thread 

### PR DESCRIPTION
**Pull request by bilthon**
The issue with the old thread being reused is fixed by lazily creating a new instance every time a new surface has been created.
I also removed a bunch of files inside the /app/build directory that were not supposed to be in the version control anyways.

### CODE REVIEW

**Comment by paulbarbu** [comment]
Thank you, kind sir!

**Comment by bilthon** [comment]
You are welcome, by the way I would like to improve your game a little bit
and maybe add a couple of functionalities. I would be willing to keep on
sending pull requests with those new things, if you don't mind of course.

Nelson Pérez

**Comment by paulbarbu** [comment]
I don't mind at all, actually I'm glad.

The only problem is that I have to use this application as a project in school (also the reason I ported it to Android Studio, in order to continue development, because until now it was almost abandoned), so if you send pull-requests I'll merge them on a separate branch until I present this to my teacher (3-4 months). Also I'll continue improving and adding functionalities, too since the collision detection is just bad, also there are no game-like features yet.

**Comment by bilthon** [comment]
Cool! In fact, I just did some changes on the collision detection
mechanism. You can check them out if you like, I'll send you another pull
request.

Where are you from?

Nelson

**Pull request merged**
